/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        TriangleNumberCalculator calculator = new TriangleNumberCalculator();

        //System.out.println(calculator.value(7121));
        System.out.println(calculator.add(7000,3000));

        // System.out.println(calculator.value(1)); // This should print out 1
        // System.out.println(calculator.value(2)); // This should print out 3
        // System.out.println(calculator.value(4)); // This should print out 10

        // System.out.println(calculator.add(1, 1)); // This should print out 2
        // System.out.println(calculator.add(2, 3)); // This should print out 9
        // System.out.println(calculator.add(4, 2)); // This should print out 13

        // System.out.println(calculator.subtract(1, 1)); // This should print out 0
        // System.out.println(calculator.subtract(2, 3)); // This should print out -3
        // System.out.println(calculator.subtract(4, 2)); // This should print out 7

        // System.out.println(calculator.multiply(1, 1)); // This should print out 1
        // System.out.println(calculator.multiply(2, 3)); // This should print out 6
        // System.out.println(calculator.multiply(4, 2)); // This should print out 20

        // System.out.println(calculator.divide(1, 1)); // This should print out 1.0
        // System.out.println(calculator.divide(3, 2)); // This should print out 1.5
        // System.out.println(calculator.divide(4, 2)); // This should print out 2.0
        
        // calculator.sequence(10); // This should print out the first 10 triangle numbers
    }
}
